### ISSUE TITLE
Generate a diff view between two similar components

### ISSUE THREAD

**Issue by Bialogs** [mitre/vulcan#139]
In the concept of releases we need to have a task that creates a diff between all controls from the previous release of the project.

**Comment by timwongj** [comment]
@rlakey can we get an example of what an acceptable changelog for this would look like?

**Comment by rlakey** [comment]
For this one instead of a document we can use this one for the git style diff view with monoco.

Maybe something at the project level to click a button to start a diff that would allow us to select two components and generate this type of result below.

Maybe with the given contraints:

- The components we select for comparison should have the same base SRG.  Web to Web, not Web to App or something like that.
- Different versions of the same SRG are ok.
- Release status is not a factor.
- This is a view only type operation, no updates.

![image](https://user-images.githubusercontent.com/14838339/152655561-da8756f1-0c31-4ef9-af5a-959a148382bb.png)
