### ISSUE TITLE
Create a `packager` or `onmibus` installer for vulcan

### ISSUE THREAD

**Issue by aaronlippold** [mitre/vulcan#40]

**Comment by rbclark** [comment]
This is in progress now, currently have omnibus properly packaging gems however am running into an issue where the source code is not being included in the resulting package, only the dependencies. Also running into an issue where omnibus caching is failing, causing me to have to use a clean container every time which is significantly slowing down builds.

**Comment by aaronlippold** [comment]
you should jump on the chefcommunity slack in the #omnibus channel and see if anyone has faced the same issue

**Comment by rbclark** [comment]
Still in progress, just providing a daily update as requested. Made more progress on this yesterday, am now working of the [supermarket omnibus](https://github.com/chef/supermarket/tree/master/omnibus) packaging as an example. The only caveat about that installer is it does not support windows, however that is most likely due to the complexity of the app (it requires redis and a bunch of other dependencies). Additionally, it was most likely just additional effort they did not need to put in since they are deploying on Linux anyway.

I have found some additional references that make it pretty clear that what we're trying to do here should be possible:
  - [Aerobase](https://aerobase.io/) builds their [server](https://github.com/aerobase/omnibus-aerobase-server) using omnibus, and they build it for Windows and Linux.
  - Most of the Chef installers (other than supermarket) support Windows, meaning most of the tools they provide also support Windows.

Some things that need to still be worked out:
  - Chef uses Postgres heavily, however they are still on version 9. This means all of their builders and installers are also on version 9. Luckily, the metasploit installer sets up postgres10 for windows. Some research will need to be done to figure out what all it will take to create a version for postgres11. Gitlab omnibus already packages postgres 11 however that is for Linux only. If necessary we can use Gitlab's definition for postgres 11 and just write a definition for Windows.
  - Test kitchen is extremely helpful for testing the building of these packages, however Chef doesn't release their official images for use outside of Chef. This means we have to use community images, which so far I've been unable to get to work. Been receiving a lot of intermittent failures involving `WinRM::WinRMAuthorizationError`. May need to add a retry option to get around this.
