### ISSUE TITLE
write unit tests for all controllers, models, views, helpers

### ISSUE THREAD

**Issue by aaronlippold** [mitre/vulcan#64]

**Comment by rbclark** [comment]
With the application cleanup currently taking place, I have decided to use `rspec` for the actual testing framework. Since the application is being ported over to a clean rails 6 app with webpacker, the first tests that need to be written are validation of the rewritten login infrastructure. Due to the complexity that is involved in the login infrastructure, I believe once we have those tests written we will have a pretty solid testing groundwork in place.
