### ISSUE TITLE
Add support for upgrading between versions of SRGs

### ISSUE THREAD

**Issue by rbclark** [mitre/vulcan#82]
Currently there are is no way to upgrade between releases of SRGs. We need to add this ability.

**Comment by rbclark** [comment]
After today's discussion, waiting until beyond V2 to implement this feature.

**Comment by timwongj** [comment]
@rbclark for the implementation of this feature, would you recommend creating a new component along with it's rules based on the new SRG and then updating check/fix/etc fields (and copying over revision history and whatnot) or would it be easier to somehow just bring in the underlying changes from a new SRG? Not sure how to go about that since creating new components/rules is straightforward, but updating only certain fields for existing rules based on changes between SRGs (which we have to detect) also seems complicated.
